Fix Travis OSX error updating python
```
Error: python 2.7.14 is already installed
To upgrade to 3.6.4_3, run `brew upgrade python`
/Users/travis/.travis/job_stages: line 57: pip3: command not found
/Users/travis/.travis/job_stages: line 57: pip3: command not found
/Users/travis/.travis/job_stages: line 57: pip3: command not found
The command "if [ "$TRAVIS_OS_NAME" == "linux" ]; then pip install
flake8; pip install flake8-docstrings; pip install python-coveralls;
elif [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; brew install
python3; pip3 install flake8; pip3 install flake8-docstrings; pip3
install python-coveralls; fi" failed and exited with 127 during .
```